server:
  port: 8086

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:h2:mem:notifications
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fasterxml.jackson.databind.JsonNode
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Custom notification settings
notification:
  email:
    from: noreply@ecommerce.com
  sms:
    provider: twilio
    account-sid: ${TWILIO_ACCOUNT_SID:your-account-sid}
    auth-token: ${TWILIO_AUTH_TOKEN:your-auth-token}
    from-number: ${TWILIO_FROM_NUMBER:+1234567890}
